version: '3.3'
services:
  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    ports:
      - '8024:8024'
      - '8124:8124'
    environment:
      axoniq_axonserver_hostname: axon-server
      axoniq_axonserver_autocluster_first: axon-server
      axoniq_axonserver_autocluster_contexts: _admin,default

    volumes:
      - data:/axonserver/data
      - events:/axonserver/events
  db:
    image: postgres
    restart: always
    container_name: postgres-axonserver
    environment:
      POSTGRES_DB: monolithe
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    expose:
      - '50006'
    ports:
      - '50006:50006'
    command: -p 50006
    volumes:
      - db:/var/lib/postgresql/data



  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "6002:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@pg.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin_data_monolithe:/var/lib/pgadmin

volumes:
  db:
    driver: local
  data:
    driver: local
  events:
    driver: local
  pgadmin_data_monolithe:


