services:
  postgres-monolithe:
    image: postgres
    restart: always
    container_name: postgres-monolithe
    volumes:
      - pg_data_monolithe:/var/lib/postgresql/data
#      - ./initdb_f.sh:/docker-entrypoint-initdb.d/initdb_f.sh
    environment:
      POSTGRES_DB: monolithe
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    #    healthcheck:
    #      test: "exit 0"
    expose:
      - '50006'
    ports:
      - '50006:50006'
    command: -p 50006


  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "6002:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@pg.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin_data_monolithe:/var/lib/pgadmin


volumes:
  pg_data_monolithe:
  pgadmin_data_monolithe:
